version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            schema: management
            host: ${POSTGRES_HOST}
            database: ${POSTGRES_DATABASE}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}"
            port: ${POSTGRES_PORT}
            ssl: true
            rawAccess: true
            migrations: true